name: netvana
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  google_nav_bar: ^5.0.7
  easy_container: ^1.0.5
  http: 
  universal_ble: 0.20.1
  convert: ^3.1.1
  modern_textfield: ^0.0.6
  filling_slider: ^0.0.3
  device_info_plus: ^9.1.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.9
  stop_watch_timer: ^3.2.1
  flutter_colorpicker: ^1.0.3
  time_picker_spinner_pop_up: ^2.0.0
  numberpicker: ^2.1.2 
  sensors_plus: ^5.0.0   # later for gyroscope
  flutter_3d_controller: ^2.2.0
  lucide_icons: ^0.257.0
  flutter_cube: ^0.1.1
  flutter_screenutil: ^5.9.3
  hugeicons: ^0.0.11
  persian_datetime_picker: ^3.2.0
  flutter_launcher_icons:

  hive: any
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.3
dev_dependencies:
  hive_generator: 
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/themes/

  fonts:
    - family: abrlb
      fonts:
        - asset: fonts/abr/AbarLow-Black.ttf
    - family: abreb
      fonts:
        - asset: fonts/abr/AbarLow-ExtraBold.ttf
    - family: estbo
      fonts:
        - asset: fonts/est/Estedad-Bold.ttf
    - family: estre
      fonts:
        - asset: fonts/est/Estedad-Regular.ttf
    - family: estsb
      fonts:
        - asset: fonts/est/Estedad-SemiBold.ttf   

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  image_path: "assets/icon.png"